ssh

diff --git a/rxhelm b/rxhelm
--- a/rxhelm
+++ b/rxhelm
@@ -3,7 +3,7 @@
 # Exit immediately if one of the commands ends with a non-zero exit code
 set -e
 
-# Used in the installer debug mode 
+# Used in the installer debug mode
 boolean() {
   case $1 in
   true) echo true ;;
@@ -79,7 +79,6 @@ line_break() {
   yes = | head -n$(($(tput cols) * 1)) | tr -d '\n'
   echo -e "\n\n\n"
 }
-    
 
 run_loading_animation() {
   i=1
@@ -101,15 +100,15 @@ download() {
 }
 
 does_command_exist() {
-  command -v "$1" > /dev/null
+  command -v "$1" >/dev/null
 }
 
 verify_downloader() {
-    # Return failure if it doesn't exist or is no executable
-    does_command_exist "$1" || return 1
+  # Return failure if it doesn't exist or is no executable
+  does_command_exist "$1" || return 1
 
-    # Set verified executable as our downloader program and return success
-    DOWNLOADER=$1
+  # Set verified executable as our downloader program and return success
+  DOWNLOADER=$1
 }
 
 check_if_can_be_installed() {
@@ -122,14 +121,14 @@ check_if_can_be_installed() {
 }
 
 shell_config_file() {
- if [[ "${SHELL}" =~ zsh ]]; then
-  SHELL_CONFIG_FILE="${HOME}/.zshrc"
- elif [[ "${SHELL}" =~ bash ]]; then
-  SHELL_CONFIG_FILE="${HOME}/.bashrc"
- fi
+  if [[ "${SHELL}" =~ zsh ]]; then
+    SHELL_CONFIG_FILE="${HOME}/.zshrc"
+  elif [[ "${SHELL}" =~ bash ]]; then
+    SHELL_CONFIG_FILE="${HOME}/.bashrc"
+  fi
 }
 
-app_installed () {
+app_installed() {
   # Return failure if it doesn't exist or is no executable
   which "$1" >/dev/null || return 1
 
@@ -138,136 +137,136 @@ app_installed () {
 
 install_snapd() {
   app_installed snap && seperator echo_success "snapd is already installed skipping.." ||
-  {
-    sudo apt-get install snapd -y >${REDIRECT} &&
-    seperator echo_success "snapd has been installed" || seperator echo_error "snapd install failed" fatal
-  }
+    {
+      sudo apt-get install snapd -y >${REDIRECT} &&
+        seperator echo_success "snapd has been installed" || seperator echo_error "snapd install failed" fatal
+    }
 }
 
 install_docker() {
   app_installed docker && seperator echo_success "docker is already installed skipping.." ||
-  {
-    echo_bold "Installing docker ..."
-    sudo apt-get install docker.io docker-compose -y >${REDIRECT} 
-    cd /etc/docker &&
-    echo -e "{ \n  \t \"insecure-registries\" : [\"localhost:32000\"] \n}" >daemon.json &&
-    seperator echo_success "docker has been installed" || seperator echo_error "docker install failed" fatal
-  }
+    {
+      echo_bold "Installing docker ..."
+      sudo apt-get install docker.io docker-compose -y >${REDIRECT}
+      cd /etc/docker &&
+        echo -e "{ \n  \t \"insecure-registries\" : [\"localhost:32000\"] \n}" >daemon.json &&
+        seperator echo_success "docker has been installed" || seperator echo_error "docker install failed" fatal
+    }
 }
 
 install_microk8s() {
   app_installed microk8s && seperator echo_success "microk8s is already installed skipping.." ||
-  {
-    sudo snap install microk8s --classic >"${REDIRECT}" &&
-    seperator echo_success "microk8s has been installed" || seperator echo_error "microk8s install failed" fatal 
-    sudo usermod -a -G microk8s "$USER"
-    sudo chown -f -R "$USER" ~/.kube
-    sudo su - "$USER" &
-    seperator echo_success "re-entered the session for the group update" || seperator echo_error "re-enter failed" fatal 
-    microk8s status --wait-ready &&
-    seperator echo_success "microk8s ready" || seperator echo_error "microk8s update status to ready has failed" fatal
-    microk8s enable dns storage helm3 registry dashboard ingress >"${REDIRECT}" &&
-    seperator echo_success "microk8s add-ons ready" || seperator echo_error "microk8s add-ons set up has failed" fatal
-    cd "$HOME"/.kube &&
-    microk8s config >config &&
-    seperator echo_success "microk8s configured" || seperator echo_error "microk8s not configured" fatal 
-  }
+    {
+      sudo snap install microk8s --classic >"${REDIRECT}" &&
+        seperator echo_success "microk8s has been installed" || seperator echo_error "microk8s install failed" fatal
+      sudo usermod -a -G microk8s "$USER"
+      sudo chown -f -R "$USER" ~/.kube
+      sudo su - "$USER" &
+      seperator echo_success "re-entered the session for the group update" || seperator echo_error "re-enter failed" fatal
+      microk8s status --wait-ready &&
+        seperator echo_success "microk8s ready" || seperator echo_error "microk8s update status to ready has failed" fatal
+      microk8s enable dns storage helm3 registry dashboard ingress >"${REDIRECT}" &&
+        seperator echo_success "microk8s add-ons ready" || seperator echo_error "microk8s add-ons set up has failed" fatal
+      cd "$HOME"/.kube &&
+        microk8s config >config &&
+        seperator echo_success "microk8s configured" || seperator echo_error "microk8s not configured" fatal
+    }
 }
 
 install_octant() {
   app_installed octant && seperator echo_success "octant is already installed skipping.." ||
-  {
-    cd "$HOME" &&
-    mkdir -p octant &&
-    cd octant &&
-    wget https://github.com/vmware-tanzu/octant/releases/download/v0.21.0/octant_0.21.0_Linux-64bit.deb &&
-    sudo dpkg -i octant_0.21.0_Linux-64bit.deb &&
-    seperator echo_success "octant has been installed" || seperator echo_error "octant install failed" fatal
-  }
+    {
+      cd "$HOME" &&
+        mkdir -p octant &&
+        cd octant &&
+        wget https://github.com/vmware-tanzu/octant/releases/download/v0.21.0/octant_0.21.0_Linux-64bit.deb &&
+        sudo dpkg -i octant_0.21.0_Linux-64bit.deb &&
+        seperator echo_success "octant has been installed" || seperator echo_error "octant install failed" fatal
+    }
 }
 
 install_requirements() {
   install_snapd &&
-  install_docker &&
-  install_microk8s &&
-  install_microk8s &&
-  install_octant &&
-  namespace_question
+    install_docker &&
+    install_microk8s &&
+    install_microk8s &&
+    install_octant &&
+    namespace_question
 }
 
-namespace_exist () {
+namespace_exist() {
   # Return failure if it doesn't exist or is no executable
   microk8s.kubectl get ns "$1" >/dev/null || return 1
 
   return 0
 }
 
-namespace_question () {
+namespace_question() {
   seperator echo_success "** Current pods in all namespaces **" &&
-  microk8s.kubectl get pods --all-namespaces &&
-  line_break &&
-  read -e -p "Please provide a name for you microk8s deployment: default [my-namespace] " NAME_SPACE
+    microk8s.kubectl get pods --all-namespaces &&
+    line_break &&
+    read -e -p "Please provide a name for you microk8s deployment: default [my-namespace] " NAME_SPACE
   NAME_SPACE=${NAME_SPACE:-my-namespace} &&
-  create_namespace
+    create_namespace
 }
 
 create_namespace() {
-  namespace_exist "$NAME_SPACE" && 
-  seperator echo_success "microk8s.kubectl namespace $NAME_SPACE already exist" && 
-  rebuild_namespace ||
-  {
-    echo_success Creating namespace $NAME_SPACE.... 
-    cd "$HOME" && 
-    microk8s.kubectl create namespace "$NAME_SPACE" &&
-    seperator echo_success "microk8s.kubectl namespace "$NAME_SPACE" has been created" || 
-    eperator echo_error "microk8s.kubectl namespace "$NAME_SPACE" failed to be created." fatal
-    password_question
-  }
+  namespace_exist "$NAME_SPACE" &&
+    seperator echo_success "microk8s.kubectl namespace $NAME_SPACE already exist" &&
+    rebuild_namespace ||
+    {
+      echo_success Creating namespace $NAME_SPACE....
+      cd "$HOME" &&
+        microk8s.kubectl create namespace "$NAME_SPACE" &&
+        seperator echo_success "microk8s.kubectl namespace "$NAME_SPACE" has been created" ||
+        eperator echo_error "microk8s.kubectl namespace "$NAME_SPACE" failed to be created." fatal
+      password_question
+    }
 }
 
 rebuild_namespace() {
   line_break &&
-  read -e -p "Would you like to delete and rebuild "$NAME_SPACE"? [Y/n] " YN
+    read -e -p "Would you like to delete and rebuild "$NAME_SPACE"? [Y/n] " YN
   [[ $YN == "y" || $YN == "Y" || $YN == "" ]] &&
-  {
-    cd "$HOME" && microk8s.kubectl delete namespace "$NAME_SPACE" &&
+    {
+      cd "$HOME" && microk8s.kubectl delete namespace "$NAME_SPACE" &&
         microk8s.kubectl create namespace "$NAME_SPACE" &&
         seperator echo_success "microk8s.kubectl namespace "$NAME_SPACE" has been created" ||
-        seperator echo_error "microk8s.kubectl namespace "$NAME_SPACE" failed to be created." 
-        password_question
-  } ||
-  upgrade_namespace
+        seperator echo_error "microk8s.kubectl namespace "$NAME_SPACE" failed to be created."
+      password_question
+    } ||
+    upgrade_namespace
 }
 
 upgrade_namespace() {
   line_break &&
-  read -e -p "Would you like to upgrade "$NAME_SPACE"? [Y/n] " YN
+    read -e -p "Would you like to upgrade "$NAME_SPACE"? [Y/n] " YN
   [[ $YN == "y" || $YN == "Y" || $YN == "" ]] &&
-  cd "$HOME" && 
+    cd "$HOME" &&
     microk8s.helm3 --namespace $NAME_SPACE upgrade --values values.yml my-release rasa-x/rasa-x ||
-    seperator echo_error "namespace $NAME_SPACE has not been upgraded. Exiting.." fatal 
+    seperator echo_error "namespace $NAME_SPACE has not been upgraded. Exiting.." fatal
 }
 
 password_question() {
   line_break &&
-  read -e -p "Please set your Rasa X username or leave blank for default. [me] " INITIAL_USERNAME
+    read -e -p "Please set your Rasa X username or leave blank for default. [me] " INITIAL_USERNAME
   INITIAL_USERNAME=${INITIAL_USERNAME:-me} &&
-  line_break &&
-  read -e -p "Please set your unique Rasa X password or leave blank and we will set a secure password for you and add it to your values.yml file in the root. " INITIAL_USER_PASSWORD
-  [[ $INITIAL_USER_PASSWORD != "" ]] && INITIAL_USER_PASSWORD=$INITIAL_USER_PASSWORD 
+    line_break &&
+    read -e -p "Please set your unique Rasa X password or leave blank and we will set a secure password for you and add it to your values.yml file in the root. " INITIAL_USER_PASSWORD
+  [[ $INITIAL_USER_PASSWORD != "" ]] && INITIAL_USER_PASSWORD=$INITIAL_USER_PASSWORD
   generate_not_yet_specified_passwords
 }
 
 # This will be run when the user is propmted to create a password or let the system create one.
 generate_not_yet_specified_passwords() {
   PASSWORD_SALT=$(get_specified_password_or_generate "${PASSWORD_SALT}") &&
-  RASA_X_TOKEN=$(get_specified_password_or_generate "${RASA_X_TOKEN}") &&
-  INITIAL_USER_PASSWORD=$(get_specified_password_or_generate "${INITIAL_USER_PASSWORD}") &&
-  RASA_TOKEN=$(get_specified_password_or_generate "${RASA_TOKEN}") &&
-  RABBITMQ_PASSWORD=$(get_specified_password_or_generate "${RABBITMQ_PASSWORD}") &&
-  POSTGRES_PASSWORD=$(get_specified_password_or_generate "${POSTGRES_PASSWORD}") &&
-  REDIS_PASSWORD=$(get_specified_password_or_generate "${REDIS_PASSWORD}") &&
-  update_values
+    RASA_X_TOKEN=$(get_specified_password_or_generate "${RASA_X_TOKEN}") &&
+    INITIAL_USER_PASSWORD=$(get_specified_password_or_generate "${INITIAL_USER_PASSWORD}") &&
+    RASA_TOKEN=$(get_specified_password_or_generate "${RASA_TOKEN}") &&
+    RABBITMQ_PASSWORD=$(get_specified_password_or_generate "${RABBITMQ_PASSWORD}") &&
+    POSTGRES_PASSWORD=$(get_specified_password_or_generate "${POSTGRES_PASSWORD}") &&
+    REDIS_PASSWORD=$(get_specified_password_or_generate "${REDIS_PASSWORD}") &&
+    update_values
 }
 
 # Generates a random password when feed nothing.
@@ -283,7 +282,7 @@ get_specified_password_or_generate() {
 update_values() {
   cd $RASA_LOCATION &&
     # Update the values.yaml file
-    sed "s/PASSWORD_SALT/${PASSWORD_SALT}/ ; s/RASA_X_TOKEN/${RASA_X_TOKEN}/ ; s/INITIAL_USERNAME/${INITIAL_USERNAME}/ ;s/INITIAL_USER_PASSWORD/${INITIAL_USER_PASSWORD}/ ; s/RASA_TOKEN/${RASA_TOKEN}/ ; s/RABBITMQ_PASSWORD/${RABBITMQ_PASSWORD}/ ; s/POSTGRES_PASSWORD/${POSTGRES_PASSWORD}/ ; s/REDIS_PASSWORD/${REDIS_PASSWORD}/ ; s/EXTERNAL_IP/${EXTERNAL_IP}/ " temp_values.yml > tmp.yml && 
+    sed "s/PASSWORD_SALT/${PASSWORD_SALT}/ ; s/RASA_X_TOKEN/${RASA_X_TOKEN}/ ; s/INITIAL_USERNAME/${INITIAL_USERNAME}/ ;s/INITIAL_USER_PASSWORD/${INITIAL_USER_PASSWORD}/ ; s/RASA_TOKEN/${RASA_TOKEN}/ ; s/RABBITMQ_PASSWORD/${RABBITMQ_PASSWORD}/ ; s/POSTGRES_PASSWORD/${POSTGRES_PASSWORD}/ ; s/REDIS_PASSWORD/${REDIS_PASSWORD}/ ; s/EXTERNAL_IP/${EXTERNAL_IP}/ " temp_values.yml >tmp.yml &&
     mv tmp.yml values.yml &&
     mv -f values.yml "$HOME" &&
     seperator echo_success "\n We have updated your temp_values.yml file and renamed it, values.yml file with updated \n \n \t EXTERNAL_IP : ${EXTERNAL_IP} \n \n \t INITIAL_USERNAME : ${INITIAL_USERNAME} \n \n \t INITIAL_USER_PASSWORD : ${INITIAL_USER_PASSWORD} \n \n Review the "$HOME"/values.yml file to find and update other advanced deployment information \n" &&
@@ -294,10 +293,10 @@ deploy_helm() {
   cd "$HOME" &&
     microk8s.helm3 repo add rasa-x https://rasahq.github.io/rasa-x-helm >${REDIRECT} &&
     microk8s.helm3 --namespace "$NAME_SPACE" install --values values.yml my-release rasa-x/rasa-x &&
-    seperator echo_success "microk8s.helm3 --namespace "$NAME_SPACE" using values.yml has been installed" || 
+    seperator echo_success "microk8s.helm3 --namespace "$NAME_SPACE" using values.yml has been installed" ||
     seperator echo_error "microk8s.helm3 --namespace "$NAME_SPACE" install Failed" fatal
 
-    echo_success "Open in your browser here http://$EXTERNAL_IP:8000/api/version to check the api status and version \n \n Or run this command in your cli \n \n microk8s.kubectl --namespace "$NAME_SPACE" get services && curl http://$EXTERNAL_IP/api/version" &&
+  echo_success "Open in your browser here http://$EXTERNAL_IP:8000/api/version to check the api status and version \n \n Or run this command in your cli \n \n microk8s.kubectl --namespace "$NAME_SPACE" get services && curl http://$EXTERNAL_IP/api/version" &&
     microk8s.kubectl --namespace "$NAME_SPACE" get services &&
     # curl http://$EXTERNAL_IP:8000/api/version &&
     seperator echo_bold "Next we will start Octant it will be available at \n http://$EXTERNAL_IP:8002/#/overview/namespace/$NAME_SPACE" &&
@@ -320,23 +319,23 @@ provide_login_credentials() {
     # Return the URL with the local IP address if the login webside is not available over the public address
     LOGIN_URL="http://${LOCAL_IP_ADDRESS}:8000/login?username=${INITIAL_USERNAME}&password=${INITIAL_USER_PASSWORD}"
   fi
-  
-  line_break 
+
+  line_break
   echo_success "You can now access Rasa X on this URL: ${LOGIN_URL}"
   line_break
   add_alias
 }
 
 add_alias() {
-    shell_config_file &&
+  shell_config_file &&
     # [ "$(grep "^NAME_SPACE=" ~/.bash*)" ] || echo "NAME_SPACE=${NAME_SPACE}" >>"${SHELL_CONFIG_FILE}"
     [ "$(grep "^alias kubectl=" ~/.bash*)" ] || echo "alias kubectl='microk8s.kubectl'" >>"${SHELL_CONFIG_FILE}"
-    [ "$(grep "^alias helm=" ~/.bash*)" ] || echo "alias helm='microk8s.helm3'" >>"${SHELL_CONFIG_FILE}"
-    [ "$(grep "^alias k=" ~/.bash*)" ] || echo "alias k=\"kubectl --namespace ${NAME_SPACE}\"" >>"${SHELL_CONFIG_FILE}" 
-    [ "$(grep "^alias h=" ~/.bash*)" ] || echo "alias h=\"helm --namespace ${NAME_SPACE}\"" >>"${SHELL_CONFIG_FILE}" 
-    [ "$(grep "^VM_IP=" ~/.bash*)" ] || echo "VM_IP=${EXTERNAL_IP}" >>"${SHELL_CONFIG_FILE}"
-    [ "$(grep "^alias api_v=" ~/.bash*)" ] || echo "alias api_v=\"curl http://${EXTERNAL_IP}:8000/api/version\"" >>"${SHELL_CONFIG_FILE}"
-    seperator echo_success "Your ~/.bashrc file is up to date. aliases available: \n \n kubectl='microk8s.kubectl' \n \n helm='microk8s.helm3' \n \n k=\"kubectl --namespace ${NAME_SPACE}\" \n \n h=\"helm --namespace ${NAME_SPACE}\" \n \n api_v=\"curl http://${EXTERNAL_IP}:8000/api/version\" \n " &&
+  [ "$(grep "^alias helm=" ~/.bash*)" ] || echo "alias helm='microk8s.helm3'" >>"${SHELL_CONFIG_FILE}"
+  [ "$(grep "^alias k=" ~/.bash*)" ] || echo "alias k=\"kubectl --namespace ${NAME_SPACE}\"" >>"${SHELL_CONFIG_FILE}"
+  [ "$(grep "^alias h=" ~/.bash*)" ] || echo "alias h=\"helm --namespace ${NAME_SPACE}\"" >>"${SHELL_CONFIG_FILE}"
+  [ "$(grep "^VM_IP=" ~/.bash*)" ] || echo "VM_IP=${EXTERNAL_IP}" >>"${SHELL_CONFIG_FILE}"
+  [ "$(grep "^alias api_v=" ~/.bash*)" ] || echo "alias api_v=\"curl http://${EXTERNAL_IP}:8000/api/version\"" >>"${SHELL_CONFIG_FILE}"
+  seperator echo_success "Your ~/.bashrc file is up to date. aliases available: \n \n kubectl='microk8s.kubectl' \n \n helm='microk8s.helm3' \n \n k=\"kubectl --namespace ${NAME_SPACE}\" \n \n h=\"helm --namespace ${NAME_SPACE}\" \n \n api_v=\"curl http://${EXTERNAL_IP}:8000/api/version\" \n " &&
     start_octant
 }
 
@@ -348,4 +347,4 @@ start_octant() {
 }
 
 # This is the start of running code
-check_if_can_be_installed 
+check_if_can_be_installed
